import type { OnboardingMember, TrainingRecord, OjtRecord, DailyReport, MentorMeeting, OnboardingSlackNotification } from "./types";

export const mockMembers: OnboardingMember[] = [
  {
    id: "ob001",
    name: "田中 花子",
    position: "フロントエンドエンジニア",
    joinedAt: "2026-03-01",
    department: "開発部",
    mentor: "木村CEO",
    ojtOwner: "鈴木HR",
    onboardingStatus: "進行中",
    condition: null,
    retentionRisk: null,
    memo: "学習意欲が高く、チームにも馴染んでいる。",
    updatedAt: "2026-04-28",
  },
  {
    id: "ob002",
    name: "佐藤 次郎",
    position: "バックエンドエンジニア",
    joinedAt: "2026-03-15",
    department: "開発部",
    mentor: "伊藤CTO",
    ojtOwner: "田中部長",
    onboardingStatus: "進行中",
    condition: null,
    retentionRisk: null,
    memo: "業務量が多く、精神的な負荷が懸念される。定期的なフォローが必要。",
    updatedAt: "2026-04-29",
  },
  {
    id: "ob003",
    name: "鈴木 三郎",
    position: "UIデザイナー",
    joinedAt: "2026-04-01",
    department: "デザイン部",
    mentor: "山本デザイン部長",
    ojtOwner: "渡辺マネージャー",
    onboardingStatus: "未開始",
    condition: null,
    retentionRisk: null,
    memo: "",
    updatedAt: "2026-04-01",
  },
  {
    id: "ob004",
    name: "山田 四郎",
    position: "プロダクトマネージャー",
    joinedAt: "2026-02-01",
    department: "事業部",
    mentor: "木村CEO",
    ojtOwner: "中田さん",
    onboardingStatus: "要フォロー",
    condition: null,
    retentionRisk: null,
    memo: "孤立感が強く、転職を検討している可能性がある。早急な面談と上長への共有が必要。",
    updatedAt: "2026-04-30",
  },
];

export const mockTrainingRecords: TrainingRecord[] = [
  {
    id: "tr001",
    memberId: "ob001",
    trainingName: "会社概要・バリュー研修",
    trainedAt: "2026-03-03",
    trainer: "鈴木HR",
    content: "会社のミッション・ビジョン・バリューについて説明。カルチャーの理解を深めた。",
    understandingLevel: 5,
    deliverableUrl: "",
    goodPoint: "積極的に質問してくれた",
    issuePoint: "",
    nextAction: "チームメンバーとの1on1を設定する",
  },
  {
    id: "tr002",
    memberId: "ob001",
    trainingName: "開発環境構築・Git研修",
    trainedAt: "2026-03-05",
    trainer: "田中部長",
    content: "ローカル開発環境のセットアップとGitフローの説明。PRのルールを確認。",
    understandingLevel: 4,
    deliverableUrl: "https://github.com/example/setup-doc",
    goodPoint: "自分でドキュメントにまとめてくれた",
    issuePoint: "Docker周りで詰まった",
    nextAction: "Dockerのトラブルシューティングガイドを共有する",
  },
  {
    id: "tr003",
    memberId: "ob002",
    trainingName: "会社概要・バリュー研修",
    trainedAt: "2026-03-17",
    trainer: "鈴木HR",
    content: "会社のミッション・ビジョン・バリューについて説明。",
    understandingLevel: 3,
    deliverableUrl: "",
    goodPoint: "質問は少なかったが理解はしている様子",
    issuePoint: "自分から積極的に発言する機会が少ない",
    nextAction: "もう少し話しやすい雰囲気作りを意識する",
  },
];

export const mockOjtRecords: OjtRecord[] = [
  {
    id: "ojt001",
    memberId: "ob001",
    recordedAt: "2026-03-15",
    projectName: "採用管理システム改善",
    taskName: "候補者リストのUI改善",
    difficulty: "中",
    progress: "完了",
    reviewer: "田中部長",
    blocker: "",
    feedback: "レスポンシブ対応まで自分で考えて実装していた",
    selfUnderstandingLevel: 4,
    reviewerComment: "想定以上のアウトプット。次はより複雑な機能を担当してもらう",
  },
  {
    id: "ojt002",
    memberId: "ob002",
    recordedAt: "2026-03-25",
    projectName: "API開発",
    taskName: "ユーザー認証エンドポイント実装",
    difficulty: "高",
    progress: "作業中",
    reviewer: "伊藤CTO",
    blocker: "JWTのリフレッシュトークン実装で詰まっている",
    feedback: "",
    selfUnderstandingLevel: 2,
    reviewerComment: "基礎的な部分は理解しているが応用に課題がある。ペアプロを検討",
  },
  {
    id: "ojt003",
    memberId: "ob002",
    recordedAt: "2026-04-10",
    projectName: "API開発",
    taskName: "エラーハンドリング実装",
    difficulty: "中",
    progress: "レビュー中",
    reviewer: "田中部長",
    blocker: "",
    feedback: "前回の課題を克服している",
    selfUnderstandingLevel: 3,
    reviewerComment: "改善が見られる。引き続きサポートを続ける",
  },
];

export const mockDailyReports: DailyReport[] = [
  {
    id: "dr001",
    memberId: "ob001",
    reportedAt: "2026-04-25",
    didToday: "候補者リストのフィルター機能を実装した。PRを出してレビュー待ち。",
    learned: "Reactの useMemo を使うことでパフォーマンス改善できることを実感した",
    blocked: "",
    nextPlan: "レビュー対応後、検索機能の実装に着手する",
    consultation: "",
    conditionScore: 5,
    workloadScore: 3,
    isolationScore: 1,
    confidenceScore: 4,
  },
  {
    id: "dr002",
    memberId: "ob001",
    reportedAt: "2026-04-28",
    didToday: "レビューコメントを対応してマージした。検索機能の設計を始めた。",
    learned: "コードレビューのフィードバックからTypeScriptの型定義の大切さを改めて認識",
    blocked: "",
    nextPlan: "検索機能のUI実装を進める",
    consultation: "",
    conditionScore: 5,
    workloadScore: 3,
    isolationScore: 1,
    confidenceScore: 5,
  },
  {
    id: "dr003",
    memberId: "ob002",
    reportedAt: "2026-04-24",
    didToday: "認証APIのデバッグを続けた。進捗は50%程度。",
    learned: "JWTのライブラリのドキュメントを読み直した",
    blocked: "リフレッシュトークンの実装が難しく、なかなか進まない",
    nextPlan: "明日CTOに相談する",
    consultation: "リフレッシュトークンの実装について相談したい",
    conditionScore: 2,
    workloadScore: 5,
    isolationScore: 4,
    confidenceScore: 2,
  },
  {
    id: "dr004",
    memberId: "ob002",
    reportedAt: "2026-04-29",
    didToday: "CTOとペアプロでリフレッシュトークンを実装できた。",
    learned: "自分一人で抱え込まずに相談することの大切さ",
    blocked: "",
    nextPlan: "エラーハンドリングのPRを出す",
    consultation: "",
    conditionScore: 3,
    workloadScore: 4,
    isolationScore: 3,
    confidenceScore: 3,
  },
  {
    id: "dr005",
    memberId: "ob004",
    reportedAt: "2026-04-27",
    didToday: "仕様書のレビューと来週のスプリント計画を行った。",
    learned: "",
    blocked: "プロダクトの方向性について疑問がある",
    nextPlan: "スプリントレビューの準備",
    consultation: "プロダクトの方向性について話し合いたい。自分がどこに貢献できているか分からない。",
    conditionScore: 2,
    workloadScore: 2,
    isolationScore: 5,
    confidenceScore: 1,
  },
];

export const mockMentorMeetings: MentorMeeting[] = [
  {
    id: "mm001",
    memberId: "ob001",
    meetingAt: "2026-04-20",
    mentor: "木村CEO",
    workCondition: "良好",
    mentalCondition: "良好",
    consultation: "次のプロジェクトでより難しいタスクに挑戦したい",
    mentorComment: "順調に成長している。積極的にチャレンジングな仕事を任せていく。",
    nextAction: "来週から新機能開発に参加させる",
    shareWithManager: "不要",
    risk: "低",
  },
  {
    id: "mm002",
    memberId: "ob002",
    meetingAt: "2026-04-22",
    mentor: "伊藤CTO",
    workCondition: "不安あり",
    mentalCondition: "不安あり",
    consultation: "業務量が多く、自分のペースで進められていない。孤立感を感じることがある。",
    mentorComment: "業務量を調整する必要がある。チームビルディングの機会を増やすべき。",
    nextAction: "業務量の見直しと週次のペアプロセッションを設定",
    shareWithManager: "必要",
    risk: "中",
  },
  {
    id: "mm003",
    memberId: "ob004",
    meetingAt: "2026-04-25",
    mentor: "木村CEO",
    workCondition: "要対応",
    mentalCondition: "要対応",
    consultation: "自分の役割が見えない。転職も検討している。",
    mentorComment: "深刻な状態。早急に上長と人事を巻き込んだサポートが必要。",
    nextAction: "人事・上長を交えた面談を来週設定する",
    shareWithManager: "必要",
    risk: "高",
  },
];

export const mockSlackNotifications: OnboardingSlackNotification[] = [
  {
    id: "osn001",
    memberId: "ob002",
    memberName: "佐藤 次郎",
    sentAt: "2026-04-22 15:30",
    channel: "#オンボーディング-アラート",
    message: "佐藤 次郎さんの面談で「上長への共有が必要」と判断されました。業務面・メンタル面ともに不安あり、リスク：中。",
  },
  {
    id: "osn002",
    memberId: "ob004",
    memberName: "山田 四郎",
    sentAt: "2026-04-25 16:00",
    channel: "#オンボーディング-アラート",
    message: "山田 四郎さんの面談で「上長への共有が必要」と判断されました。業務面・メンタル面ともに要対応、リスク：高。早急な対応が必要です。",
  },
  {
    id: "osn003",
    memberId: "ob002",
    memberName: "佐藤 次郎",
    sentAt: "2026-04-24 18:00",
    channel: "#オンボーディング-アラート",
    message: "佐藤 次郎さんの日報に相談事項が記載されています：「リフレッシュトークンの実装について相談したい」",
  },
  {
    id: "osn004",
    memberId: "ob004",
    memberName: "山田 四郎",
    sentAt: "2026-04-27 18:00",
    channel: "#オンボーディング-アラート",
    message: "山田 四郎さんの日報に相談事項が記載されています：「プロダクトの方向性について話し合いたい。自分がどこに貢献できているか分からない。」",
  },
  {
    id: "osn005",
    memberId: "ob004",
    memberName: "山田 四郎",
    sentAt: "2026-04-30 10:00",
    channel: "#オンボーディング-アラート",
    message: "山田 四郎さんの状態が「要対応」、定着リスクが「高」に更新されました。",
  },
];
