import { Candidate, InterviewQuestion, InterviewRecord, InterviewStage, SlackNotification, EmailHistory } from "./types";

export const mockCandidates: Candidate[] = [
  {
    id: "c001",
    name: "山田太郎",
    nameKana: "やまだたろう",
    position: "フロントエンドエンジニア",
    status: "書類選考",
    appliedAt: "2024-04-01",
    email: "yamada.taro@example.com",
    phone: "090-1234-5678",
    age: "28",
    interviewers: ["田中部長"],
    memo: "Reactの経験あり。GitHubのポートフォリオ確認済み。",
    updatedAt: "2024-04-03",
    portfolioUrl: "https://github.com",
    interviewRecords: [],
  },
  {
    id: "c002",
    name: "佐藤花子",
    nameKana: "さとうはなこ",
    position: "バックエンドエンジニア",
    status: "一次面接",
    appliedAt: "2024-03-28",
    email: "sato.hanako@example.com",
    phone: "03-9876-5432",
    age: "32",
    interviewers: ["中田さん", "田中部長"],
    memo: "Go言語の経験が豊富。前職はスタートアップ。",
    updatedAt: "2024-04-05",
    interviewRecords: [
      {
        id: "ir001",
        stageName: "一次面接",
        date: "2024-04-12",
        interviewers: ["中田さん", "田中部長"],
        notes: "Go言語の深い理解を確認。マイクロサービスの実装経験もあり好印象。コミュニケーションも良好で、技術的な説明も分かりやすかった。チームへの馴染みやすさも感じられた。",
        rating: 4,
        result: "通過",
      },
    ],
  },
  {
    id: "c003",
    name: "鈴木一郎",
    nameKana: "すずきいちろう",
    position: "プロダクトマネージャー",
    status: "最終面接",
    appliedAt: "2024-03-20",
    email: "suzuki.ichiro@example.com",
    phone: "080-3456-7890",
    age: "35",
    interviewers: ["木村CEO", "伊藤CTO"],
    memo: "B to B SaaSの経験あり。英語も問題なし。",
    updatedAt: "2024-04-08",
    interviewRecords: [
      {
        id: "ir002",
        stageName: "一次面接",
        date: "2024-04-05",
        interviewers: ["田中部長"],
        notes: "プロダクト戦略の思考が明確。KPI設計やロードマップの引き方に説得力があった。英語でも簡単な質疑応答を実施、問題なし。",
        rating: 5,
        result: "通過",
      },
      {
        id: "ir003",
        stageName: "最終面接",
        date: "2024-04-10",
        interviewers: ["木村CEO", "伊藤CTO"],
        notes: "ビジョンへの共感度が高い。入社意欲も非常に強い。技術バックグラウンドも十分でエンジニアとの連携も期待できる。",
        rating: 5,
        result: "通過",
      },
    ],
  },
  {
    id: "c004",
    name: "田中みどり",
    nameKana: "たなかみどり",
    position: "UIデザイナー",
    status: "内定",
    appliedAt: "2024-03-15",
    email: "tanaka.midori@example.com",
    phone: "070-2345-6789",
    age: "26",
    interviewers: ["山本デザイン部長"],
    memo: "Figmaの経験豊富。ポートフォリオ高評価。入社意欲も高い。",
    updatedAt: "2024-04-10",
    interviewRecords: [
      {
        id: "ir004",
        stageName: "一次面接",
        date: "2024-03-25",
        interviewers: ["山本デザイン部長"],
        notes: "Figmaでのプロトタイプ制作フローを詳細に説明。ユーザー調査の経験もあり。デザインシステム構築の知見が特に印象的だった。",
        rating: 5,
        result: "通過",
      },
    ],
  },
  {
    id: "c005",
    name: "伊藤健太",
    nameKana: "いとうけんた",
    position: "フロントエンドエンジニア",
    status: "応募受付",
    appliedAt: "2024-04-10",
    email: "ito.kenta@example.com",
    phone: "",
    age: "",
    interviewers: [],
    memo: "",
    updatedAt: "2024-04-10",
    interviewRecords: [],
  },
  {
    id: "c006",
    name: "渡辺さくら",
    nameKana: "わたなべさくら",
    position: "バックエンドエンジニア",
    status: "不採用",
    appliedAt: "2024-03-10",
    email: "watanabe.sakura@example.com",
    phone: "090-8765-4321",
    age: "29",
    interviewers: ["中田さん"],
    memo: "技術スキルのミスマッチ。別ポジションでの再応募は歓迎。",
    updatedAt: "2024-04-07",
    interviewRecords: [
      {
        id: "ir005",
        stageName: "一次面接",
        date: "2024-03-18",
        interviewers: ["中田さん"],
        notes: "Pythonの経験が主でGoは独学レベル。現時点では要求スペックに届かない印象。ポテンシャルはあるが即戦力としては難しい。",
        rating: 2,
        result: "不採用",
      },
    ],
  },
  {
    id: "c007",
    name: "中村達也",
    nameKana: "なかむらたつや",
    position: "インフラエンジニア",
    status: "辞退",
    appliedAt: "2024-03-25",
    email: "nakamura.tatsuya@example.com",
    phone: "06-1234-5678",
    age: "31",
    interviewers: ["田中部長"],
    memo: "他社からオファーを受けて辞退。関係は良好。",
    updatedAt: "2024-04-06",
    interviewRecords: [],
  },
  {
    id: "c008",
    name: "小林真奈",
    nameKana: "こばやしまな",
    position: "プロダクトマネージャー",
    status: "一次面接",
    appliedAt: "2024-04-02",
    email: "kobayashi.mana@example.com",
    phone: "080-9012-3456",
    age: "33",
    interviewers: ["木村CEO"],
    memo: "大手EC出身。データドリブンな思考を持つ。",
    updatedAt: "2024-04-09",
    interviewRecords: [],
  },
];

export const mockInterviewStages: InterviewStage[] = [
  {
    id: "stage001",
    name: "書類選考",
    order: 1,
    interviewers: ["鈴木HR"],
    format: "オンライン",
    durationMinutes: 0,
    description: "履歴書・職務経歴書・ポートフォリオを確認し、基本的なスキルと経験を評価する。",
  },
  {
    id: "stage002",
    name: "一次面接",
    order: 2,
    interviewers: ["田中部長", "中田さん"],
    format: "オンライン",
    durationMinutes: 60,
    description: "技術スキルとカルチャーフィットを確認する。実務経験・過去のプロジェクトをヒアリング。",
  },
  {
    id: "stage003",
    name: "最終面接",
    order: 3,
    interviewers: ["木村CEO", "伊藤CTO"],
    format: "対面",
    durationMinutes: 60,
    description: "経営層による最終確認。入社意欲・キャリアビジョン・チームフィットを評価する。",
  },
];

export const mockSlackNotifications: SlackNotification[] = [
  {
    id: "s001",
    candidateId: "c001",
    candidateName: "山田太郎",
    sentAt: "2024-04-03 10:15",
    channel: "#採用チャンネル",
    message: "山田太郎さんが書類選考に登録されました。",
  },
  {
    id: "s002",
    candidateId: "c002",
    candidateName: "佐藤花子",
    sentAt: "2024-04-05 14:30",
    channel: "#採用チャンネル",
    message: "佐藤花子さんの一次面接が中田さん・田中部長で登録されました。",
  },
  {
    id: "s003",
    candidateId: "c003",
    candidateName: "鈴木一郎",
    sentAt: "2024-04-08 09:00",
    channel: "#採用チャンネル",
    message: "鈴木一郎さんが最終面接ステータスに更新されました。",
  },
  {
    id: "s004",
    candidateId: "c004",
    candidateName: "田中みどり",
    sentAt: "2024-04-10 16:45",
    channel: "#採用チャンネル",
    message: "田中みどりさんに内定を出しました。",
  },
  {
    id: "s005",
    candidateId: "c008",
    candidateName: "小林真奈",
    sentAt: "2024-04-09 11:20",
    channel: "面接官DM",
    message: "小林真奈さんの一次面接が木村CEOで登録されました。",
  },
];

export const mockEmailHistories: EmailHistory[] = [
  {
    id: "e001",
    candidateId: "c002",
    candidateName: "佐藤花子",
    sentAt: "2024-04-05 15:00",
    direction: "送信",
    subject: "一次面接のご案内",
    summary: "4月12日（金）14時より弊社にて一次面接を実施する旨をご案内。",
  },
  {
    id: "e002",
    candidateId: "c002",
    candidateName: "佐藤花子",
    sentAt: "2024-04-05 17:30",
    direction: "受信",
    subject: "Re: 一次面接のご案内",
    summary: "面接日程のご確認をいただきました。ご参加の意思表示あり。",
  },
  {
    id: "e003",
    candidateId: "c003",
    candidateName: "鈴木一郎",
    sentAt: "2024-04-08 09:30",
    direction: "送信",
    subject: "最終面接のご案内",
    summary: "4月15日（月）10時より最終面接の実施をご案内。",
  },
  {
    id: "e004",
    candidateId: "c004",
    candidateName: "田中みどり",
    sentAt: "2024-04-10 17:00",
    direction: "送信",
    subject: "内定のご通知",
    summary: "内定通知書を添付の上、入社意思確認をご連絡。",
  },
  {
    id: "e005",
    candidateId: "c001",
    candidateName: "山田太郎",
    sentAt: "2024-04-03 10:30",
    direction: "送信",
    subject: "ポートフォリオ送付のお礼",
    summary: "書類選考通過のご連絡と、次のステップについてご案内。",
  },
  {
    id: "e006",
    candidateId: "c008",
    candidateName: "小林真奈",
    sentAt: "2024-04-09 12:00",
    direction: "送信",
    subject: "一次面接のご案内",
    summary: "4月16日（火）13時より一次面接の実施をご案内。",
  },
];

export const mockInterviewQuestions: InterviewQuestion[] = [
  // 一次面接
  {
    id: "q001", stage: "一次面接", tags: ["志望動機"],
    text: "当社を志望した理由を教えてください。",
    modelAnswer: "良い回答は「企業研究に基づいた具体性」と「自身のキャリアとの接続」が鍵。「御社の〇〇というプロダクト・文化・ビジョンに共感し、自分の△△という経験・強みを活かして□□に貢献したい」という構成が理想。抽象的な「成長できそう」「雰囲気が良い」は避けること。",
  },
  {
    id: "q002", stage: "一次面接", tags: ["志望動機"],
    text: "他に受けている企業はありますか？当社の志望度は？",
    modelAnswer: "志望度の高さを正直かつ前向きに伝えることが重要。「同業他社も検討していますが、御社は〇〇という点が他と異なり第一志望です」と軸を明確にする。内定辞退リスクの確認が目的なので、御社が第一志望であることを根拠とともに伝えられると◎。",
  },
  {
    id: "q003", stage: "一次面接", tags: ["経歴・スキル"],
    text: "これまでの経歴の中で最も力を入れた仕事を教えてください。",
    modelAnswer: "STAR法（Situation・Task・Action・Result）で構造的に話せているかを見る。「〇〇という状況で、△△という課題があり、自分は□□というアクションを取り、結果として◇◇を達成した」という流れ。数字や具体的な成果があると説得力が増す。",
  },
  {
    id: "q004", stage: "一次面接", tags: ["経歴・スキル"],
    text: "あなたの強みと弱みを教えてください。",
    modelAnswer: "強みは職務要件に結びついたものを選び、具体的なエピソードで裏付ける。弱みは「致命的な欠点」ではなく「改善中の課題」として話すこと。「〇〇が弱みでしたが、△△という取り組みで改善し、現在は□□まで対処できるようになりました」の形が理想。",
  },
  {
    id: "q005", stage: "一次面接", tags: ["経歴・スキル"],
    text: "チームで取り組んだプロジェクトで、あなたの役割は何でしたか？",
    modelAnswer: "チームの中での自分の貢献と、協調性・リーダーシップのバランスを確認する質問。「チーム全体で〇〇を目標とし、自分は△△の役割を担い、□□という工夫で貢献した」と具体的に話せるかがポイント。「チームが成功したから私も」という他力本願な答えは避ける。",
  },
  {
    id: "q006", stage: "一次面接", tags: ["思考・問題解決"],
    text: "困難な課題に直面したとき、どのように対処しましたか？具体的なエピソードを教えてください。",
    modelAnswer: "問題への向き合い方・思考プロセス・行動力を見る。「〇〇という問題が起き、まず△△の原因を特定し、□□という対策を実行した。結果◇◇となり、〜という学びを得た」の流れが理想。困難を他者のせいにせず、自分の判断・行動にフォーカスできているかがキー。",
  },
  {
    id: "q007", stage: "一次面接", tags: ["思考・問題解決"],
    text: "複数のタスクが重なったとき、優先順位はどう決めますか？",
    modelAnswer: "タスク管理能力と意思決定のロジックを確認する。「締め切り・重要度・依存関係の3軸で整理し、まず〇〇を優先する」など具体的な基準を持っているかがポイント。「都度上司に確認する」だけでは主体性が低く見える。実際のエピソードとセットで話せると良い。",
  },
  // 二次面接
  {
    id: "q008", stage: "二次面接", tags: ["カルチャーフィット"],
    text: "理想の職場環境はどのようなものですか？",
    modelAnswer: "自社の文化・風土とのマッチ度を確認する質問。「心理的安全性が高く、成長機会がある環境」などは一般的すぎる。「〇〇というスタイルで仕事ができる環境」と具体的に述べ、「御社の△△という文化がまさにそれに合致している」と接続できると◎。",
  },
  {
    id: "q009", stage: "二次面接", tags: ["カルチャーフィット"],
    text: "フィードバックをもらったとき、どのように受け止めますか？",
    modelAnswer: "成長意欲と素直さ・ストレス耐性を測る。「フィードバックは成長のヒントと捉え、まず感謝してから内容を咀嚼し実践する」という姿勢が理想。過去に厳しいフィードバックを受けた具体的なエピソードとセットで話せると信憑性が増す。",
  },
  {
    id: "q010", stage: "二次面接", tags: ["経歴・スキル"],
    text: "前職で最も成果を上げた実績と、そこで学んだことを教えてください。",
    modelAnswer: "実績の再現性と学習能力を確認する。数字・規模感を含めた成果（「売上〇%向上」「チーム生産性が△倍」など）と、その過程で得た学びを結びつけて話せるかがポイント。「たまたまうまくいった」ではなく「この工夫が成果につながった」という因果関係が見えると高評価。",
  },
  {
    id: "q011", stage: "二次面接", tags: ["思考・問題解決"],
    text: "意見の対立があったとき、どのように解決しましたか？",
    modelAnswer: "対人スキルと論理的な問題解決能力を見る。「感情的にならず、まず相手の主張の背景にある目的を理解し、共通の目標に立ち返って議論した」という姿勢が理想。自分の意見を押し通した or 黙って従った、の両極端は低評価。",
  },
  {
    id: "q012", stage: "二次面接", tags: ["カルチャーフィット"],
    text: "どのようなチームで働くときにパフォーマンスが上がりますか？",
    modelAnswer: "自社チームの特性と候補者の相性を確認する。「〇〇という役割分担がある」「△△のような意思決定スタイル」など具体的な条件を挙げ、過去の経験と結びつけて説明できるかがポイント。「なんでもいい」は適応力ではなく思考の浅さに見える。",
  },
  // 最終面接
  {
    id: "q013", stage: "最終面接", tags: ["将来・キャリア"],
    text: "5年後、どのようなキャリアを描いていますか？",
    modelAnswer: "長期的なビジョンと自社での活躍イメージを確認する。「〇〇のスキルを磨き、△△のような役割で□□に貢献したい」と具体的に話し、その実現手段として「御社でなければならない理由」を添えると説得力が上がる。曖昧な「成長したい」は避ける。",
  },
  {
    id: "q014", stage: "最終面接", tags: ["将来・キャリア"],
    text: "当社でどのように成長したいと考えていますか？",
    modelAnswer: "入社後の活躍イメージと定着度を測る。「〇〇というスキル・経験を積み、△△という形で会社に貢献しながら成長したい」と、Give & Takeの構造で話せると良い。「もらう」側だけの発言（「成長させてもらいたい」）は受け身な印象を与えるので注意。",
  },
  {
    id: "q015", stage: "最終面接", tags: ["志望動機"],
    text: "最終的に当社を選ぶ決め手は何ですか？",
    modelAnswer: "内定受諾の確度と志望の本気度を測る最重要質問。「〇〇という点が他社にない御社の強みであり、自分の△△という志向と一致している。内定をいただければ御社を選ぶ意思が固まっています」と明確に伝えることで採用担当の安心感につながる。",
  },
  {
    id: "q016", stage: "最終面接", tags: ["逆質問対策"],
    text: "入社後に期待される役割・ミッションは何ですか？",
    modelAnswer: "候補者からの逆質問としても有効。「入社後に最も注力してほしいことは何ですか？」と聞くことで、会社側の期待値と自分のスキルのギャップを事前に把握できる。聞いた後は「その点については〇〇という経験があります」と自己PRにつなげると◎。",
  },
  {
    id: "q017", stage: "最終面接", tags: ["逆質問対策"],
    text: "現在のチームが抱えている最大の課題は何ですか？",
    modelAnswer: "逆質問として使うと、課題解決への貢献意欲をアピールできる。回答を受けたら「その課題に対して、私は〇〇という経験で□□のような貢献ができると考えています」と返すと面接官に強い印象を与える。会社のリアルな状況把握にも役立つ良質な質問。",
  },
];
